# Generated by Django 4.2.7 on 2023-11-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_marks_student_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='subject',
            new_name='subject_id',
        ),
    ]
