# Generated by Django 4.2.7 on 2023-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_student_marks_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='marks',
            name='subject_name',
            field=models.CharField(default='math', max_length=25),
            preserve_default=False,
        ),
    ]
