# Generated by Django 4.2.7 on 2023-11-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_marks_subject_id_marks_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('D', 'Developer')], max_length=1),
        ),
    ]
