# Generated by Django 4.2.7 on 2023-11-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
