# Generated by Django 4.2.7 on 2023-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ticket_previous_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='previous_ticket',
            field=models.IntegerField(),
        ),
    ]
