# Generated by Django 4.2.7 on 2023-11-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ticket_previous_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='previous_ticket',
            new_name='next',
        ),
    ]
