# Generated by Django 4.2.7 on 2023-12-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_futureticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureticket',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
